In [1]:
import torch
from vgg_models import *
import numpy as np
import math
import random

In [496]:
model = VGG('VGG16')
w = model.state_dict()
for key in w.keys():
    w[key] = w[key]*random.randrange(-5,6)
    

In [66]:
torch.randint(4,(1, 1)).data[0].numpy()[0]+2

2

In [156]:
np.random.randn()*np.random.randint(2,5)

-1.8715440366113543

In [351]:
long(np.random.randn()*np.random.randint(2,5))

NameError: name 'long' is not defined

In [549]:
t=torch.randn(1)*random.randrange(1,5)
t2 = torch.empty([])
t.size(0)
t2.size()

0

In [639]:
# # Linear algebra operations
# t = torch.ones( 3,3 )
# print(t)
torch.randn(1)*5

tensor([-1.8249])

In [704]:
torch.rand(1)*5

tensor([0.2042])

In [712]:
x = torch.randn(3, 3)
print(x)
t = torch.as_strided(x, (2, 2), (1, 2))
print('\n\n')
print(t)

tensor([[ 1.1200, -1.2872,  1.2088],
        [ 0.7745, -0.5289, -1.4088],
        [ 0.1939, -1.1791, -1.2480]])



tensor([[ 1.1200,  1.2088],
        [-1.2872,  0.7745]])


In [757]:
torch.tensor(random.randrange(2,6))

tensor(5)

In [794]:
r2 = torch.tensor((max(torch.rand(1)*5,2)))
r2

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([2.3104])

In [834]:
torch.randn(1)

tensor([0.1297])

In [17]:
a = np.asarray([0,1,1,1,0])
b = np.asarray([0,1,1,1,0])
(a==b).sum()/len(a)
print('a {}%'.format(10))

a 10%
